language: node_js
node_js:
  - "lts/*"
addons:
  sonarcloud:
    organization: "discipl" # the key of the org you chose at step #3
script:
  - npm run lint
  - npm audit
  # for test purposes, we ignore the fact that the certificate is self-signed
  - npm test

after_success:
  - npm run coverage
  - 'if [ ! -z "$SONAR_TOKEN" ]; then sonar-scanner; fi'
